name: lpf-env
channels:  
  - conda-forge
dependencies:  
  - python>=3.8  
  - numpy  
  - pandas  
  - netcdf4  
  - pip  
  - setuptools
  - pytest
  - conda-build
  - conda-verify
  - anaconda-client