{% set name = "loopprojectfile" %
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/Loop3D/LoopProjectFile.git

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - numpy
    - pandas
    - netcdf4

about:
  home: "https://github.com/Loop3D/LoopProjectFile.git"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "An interface between the Loop backend and GUI"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - yohanderose