name: Build Conda Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJSON(vars.BUILD_OS) }}
        python: ${{ fromJSON(vars.PYTHON_VERSIONS) }}

    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python }}

      - uses: actions/checkout@v4

      - run: git submodule update --init --recursive

      - run: |
          conda update -n base -c defaults --all -y
          conda config --set solver classic
          conda install -n base -c conda-forge gxx_linux-64 sysroot_linux-64 libgcc-ng libstdcxx-ng -y
          conda install -c conda-forge conda-build anaconda-client conda-verify -y
          conda install -c conda-forge -c loop3d --file requirements.txt -y

      - env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          conda build -c anaconda -c conda-forge -c loop3d --output-folder conda conda --python ${{ matrix.python }}
          anaconda upload --label main conda/*/*.tar.bz2

      - uses: actions/upload-artifact@v4
        with:
          name: conda-build-${{ matrix.os }}-${{ matrix.python }}
          path: conda
