name: release-please
on: [push, pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  # linting:
  #   name: Linting
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install black ruff
  #     - name: Autoformat with black
  #       run: |
  #         black .
  #     - name: Lint with ruff
  #       run: |
  #         ruff check LoopProjectFile --fix
  #     - uses: stefanzweifel/git-auto-commit-action@v5
  #       with:
  #         commit_message: "style: style fixes by ruff and autoformatting by black"
          

  
    
  pip-build-wheels:
    name: Build Wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ["ubuntu-latest","macosx-latest","windows-latest"]

    steps:
      - uses: actions/checkout@v4

      - name: Build Wheels
        run: |
          python -m pip install --upgrade pip
          pip install netCDF4>=1.5.4 
          pip install build numpy pandas pytest
          python -m build --wheel

      - uses: actions/upload-artifact@v4
        with:
          name: loopprojectfile-wheels-${{ matrix.os }}
          path: dist/*.whl
          compression-level: 0

  
